### ISSUE TITLE
Morning Review 11/05/2020

### ISSUE THREAD

**Issue by SigmaSam** [SigmaSam/Desing-and-Tear-Down-Samuel-Juan#3]

**Comment by asiimwedismas** [comment]
in the CSS styles, when you want to performs reset, use the universal selector(*) to target all elements at once rather than including each element individually

**Comment by shubhsk88** [comment]
Try to use the box model in your HTML it solves some of the problems which you have with measuring and try not to use the `<br> ` code in your HTML. Otherwise code is written very well

**Comment by asiimwedismas** [comment]
> Try to use the box model in your HTML it solves some of the problems which you have with measuring and try not to use the `<br> ` code in your HTML. Otherwise code is written very well

Adding to that, use <br> to break up text instead
